name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者你希望触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Setup SSH agent for deployment
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_COMPANY }}

      - name: Configure Git to use company SSH config
        run: |
          git config --global url."git@github.com-company:".insteadOf "git@github.com:"

      - name: Deploy to GitHub Pages
        run: pnpm run deploy 